packages:
  - 'packages/*'
  - 'apps/*'
  - 'tests/*'
allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  aws-sdk: true
  browser-tabs-lock: true
  core-js: true
  es5-ext: true
  esbuild: true
  msw: true
  protobufjs: true
  serverless: true
  unrs-resolver: true
