packages:
  - 'packages/*'
  - 'apps/*'
  - 'tests/*'
onlyBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - aws-sdk
  - browser-tabs-lock
  - core-js
  - es5-ext
  - esbuild
  - msw
  - protobufjs
  - serverless
  - unrs-resolver
