export {
  type DataType,
  type IService,
  type IServiceApp,
  type IServiceConfig,
  type IVariable,
  MethodName,
  MethodNameSchema,
  ServiceConfigSchema,
  ServiceName,
  ServiceNameSchema,
  ServiceSchema,
  ServiceType,
  ServiceTypeSchema,
  VariableSchema,
  VariableType,
  VariableTypeSchema,
  DataTypeSchema,
} from '@baita/shared'
