export const LAMBDA_TIMEOUT_BUFFER_MS = 200
export const LOG_LOOKBACK_DAYS = 10
export const LOG_QUERY_LIMIT = 20
export const SQS_RETENTION_SECONDS = 60 * 60 * 24 * 2
export const CONTENT_BATCH_LIMIT = 10
export const CODE_EXECUTION_TIMEOUT_MS = 5000
export const DISABLED_SCHEDULE_EXPRESSION = 'cron(0 0 1 * ? 2030)'
